---
Name: form-extras
After:
- 'framework/*'
- 'cms/*'
---
Director:
  rules:
    '__upload//$Action/$ID/$Name': 'AjaxUploadController'
FormField:
  extensions:
    - 'TooltipFieldExtension'
FormExtraJquery:
  # Version can be: framework, v1 or v2
  jquery_version: 'framework'
  jquery_v1: '1.12.4'
  jquery_v2: '2.2.4'
  jquery_migrate: 'auto_browser'
  jquery_ui_version: 'framework'
  jquery_ui_theme: 'default'
BaseUploadField:
  use_subsite_integration: true
BirthDateField:
  year_range: 120 # JD-2019.10.24 Make year range configurable
ImageUploadField:
  # default size in MB
  default_max_file_size: 4
  default_allowed_extensions: [jpg,jpeg,png,gif]
CMSMain:
  extensions:
    - 'HasOneEditUpdateFormExtension'
GridFieldDetailForm_ItemRequest:
  extensions:
    - 'HasOneEditUpdateFormExtension'
DataObject:
  extensions:
    - 'HasOneEditDataObjectExtension'
ChosenField:
  rtl: false
Select2Field:
  rtl: false
  use_v3: false
SexyPasswordField:
  show_password_constraints: true
  enable_show_hide: true
SimpleTinyMceField:
  menubar: false
  skin: 'lightgray'
  toolbar: 'cut copy paste undo redo | removeformat | nulllist numlist blockquote | alignleft aligncenter alignright | formatselect | bold italic textcolor hr | link image media'
  simple_toolbar: 'removeformat | nulllist numlist blockquote | bold italic textcolor hr | link image media'
  plugins: 'autolink autoresize link lists hr anchor image media paste textcolor emoticons'
CropboxField:
  use_hammer: true
  use_mousewheel: true
# Apply it yourself
# Image:
#   extensions:
#     - 'CropboxImage'
LeftAndMain:
  extensions:
    - FormExtraLeftAndMainExtension
